networks:
  default: null
  proxy:
    external:
      name: proxy_default

services:
  votes:
    image: client
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CERT_NAME: wildcard
      VIRTUAL_HOST: votes.wolbodo.nl

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      CERT_NAME: wildcard
      VIRTUAL_HOST: mercure.wolbodo.nl

      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://votes.wolbodo/ https://votes.wolbodo.nl
        anonymous
        demo
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config: