networks:
  default:
    external:
      name: proxy_default

services:
  votes:
    image: wolbodo/votes:latest
    restart: unless-stopped
    environment:
      MERCURE_JWT_SECRET: $MERCURE_JWT_SECRET
      CERT_NAME: wildcard
      VIRTUAL_HOST: vote.wolbodo.nl

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      CERT_NAME: wildcard
      VIRTUAL_HOST: mercure.wolbodo.nl
      SERVER_NAME: 'mercure.wolbodo.nl:80'

      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://vote.wolbodo https://vote.wolbodo.nl
        ui
        subscriptions
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config: